Exception in thread Debugger Thread:
Traceback (most recent call last):
  File "C:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Users\Thomas\Documents\DarkPython\darkpython\debugger.py", line 83, in run
    if globals is None:
UnboundLocalError: local variable 'globals' referenced before assignment

Exception in thread Debugger Thread:
Traceback (most recent call last):
  File "C:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Users\Thomas\Documents\DarkPython\darkpython\debugger.py", line 83, in run
    if globals is None:
UnboundLocalError: local variable 'globals' referenced before assignment

Exception in thread Debugger Thread:
Traceback (most recent call last):
  File "C:\Python27x86\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Users\Thomas\Documents\DarkPython\darkpython\debugger.py", line 92, in run
    except BdbQuit:
NameError: name 'BdbQuit' is not defined

